package admin

import (
	"embed"
	"log/slog"
	"net/http"
	"sync"
	"time"

	"openlist-tvbox/internal/auth"
	"openlist-tvbox/internal/config"
	"openlist-tvbox/internal/logging"
)

const (
	envAdminCode      = "OPENLIST_TVBOX_ADMIN_ACCESS_CODE"
	envAdminCodeHash  = "OPENLIST_TVBOX_ADMIN_ACCESS_CODE_HASH"
	secretFileName    = "admin_access_code_hash"
	setupCodeFileName = "admin_setup_code"
	maxConfigBodySize = 1 << 20
	sessionCookieName = "openlist_tvbox_admin_session"
	sessionTTL        = 12 * time.Hour
	maxAdminSessions  = 128
)

var adminBcryptCost = auth.DefaultBcryptCost

// Admin UI assets are generated by `pnpm build:admin` / `pnpm build`.
// assets/placeholder.txt keeps this embed pattern valid in clean Go builds.
//
//go:embed assets/*
var adminAssets embed.FS

type Server struct {
	configPath    string
	logger        *slog.Logger
	hash          string
	setupCodePath string
	setupCode     string
	onSaved       func(*config.Config)
	saveMu        sync.Mutex
	setupMu       sync.Mutex
	authLimiter   *auth.FailureLimiter
	logBuffer     *logging.Buffer
	shutdown      chan struct{}
	shutdownOnce  sync.Once
	sessionMu     sync.Mutex
	sessions      map[string]adminSession
	trustMu       sync.RWMutex
	trustXFF      bool
	publicBaseURL string
}

type adminSession struct {
	CreatedAt time.Time
	ExpiresAt time.Time
}

type Options struct {
	ConfigPath string
	Listen     string
	Logger     *slog.Logger
	LogBuffer  *logging.Buffer
	OnSaved    func(*config.Config)
}

func NewServer(opts Options) (*Server, error) {
	state, err := loadAdminState(opts.ConfigPath)
	if err != nil {
		return nil, err
	}
	trustXFF := false
	publicBaseURL := ""
	if cfg, err := config.Load(opts.ConfigPath); err == nil {
		trustXFF = cfg.TrustForwardedHeaders
		publicBaseURL = cfg.PublicBaseURL
	}
	if opts.Logger != nil {
		if state.Hash != "" {
			opts.Logger.Info("admin access code loaded")
		} else {
			opts.Logger.Warn("admin setup required; use the setup code file to create an access code", "admin_url", adminURL(opts.Listen), "setup_code_path", state.SetupCodePath)
		}
	}
	return &Server{
		configPath:    opts.ConfigPath,
		logger:        opts.Logger,
		hash:          state.Hash,
		setupCodePath: state.SetupCodePath,
		setupCode:     state.SetupCode,
		onSaved:       opts.OnSaved,
		authLimiter:   auth.NewFailureLimiter(auth.DefaultFailureLimit, auth.DefaultFailureCooldown),
		logBuffer:     opts.LogBuffer,
		shutdown:      make(chan struct{}),
		sessions:      map[string]adminSession{},
		trustXFF:      trustXFF,
		publicBaseURL: publicBaseURL,
	}, nil
}

func (s *Server) Shutdown() {
	s.shutdownOnce.Do(func() {
		close(s.shutdown)
	})
}

func (s *Server) Handler() http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("POST /admin/setup", s.requireSameOrigin(s.setup))
	mux.HandleFunc("POST /admin/login", s.requireSameOrigin(s.login))
	mux.HandleFunc("POST /admin/logout", s.requireSameOrigin(s.logout))
	mux.HandleFunc("POST /admin/access-code", s.requireSameOrigin(s.requireAuth(s.updateAdminAccessCode)))
	mux.HandleFunc("GET /admin/session", s.session)
	mux.HandleFunc("GET /admin/about", s.requireAuth(s.about))
	mux.HandleFunc("GET /admin/config/meta", s.requireAuth(s.meta))
	mux.HandleFunc("GET /admin/config", s.requireAuth(s.getConfig))
	mux.HandleFunc("GET /admin/logs", s.requireAuth(s.logs))
	mux.HandleFunc("GET /admin/logs/stream", s.requireAuth(s.streamLogs))
	mux.HandleFunc("POST /admin/config/validate", s.requireSameOrigin(s.requireAuth(s.validateConfig)))
	mux.HandleFunc("POST /admin/backend/test", s.requireSameOrigin(s.requireAuth(s.testBackend)))
	mux.HandleFunc("PUT /admin/config", s.requireSameOrigin(s.requireAuth(s.putConfig)))
	mux.HandleFunc("GET /admin/assets/", s.asset)
	mux.HandleFunc("GET /admin", s.index)
	mux.HandleFunc("GET /admin/", s.index)
	return mux
}
